### ISSUE TITLE
Test is loading code from a function pointer

### ISSUE THREAD

**Issue by RalfJung** [koutheir/selinux#4]
This line looks like it doesn't do what it was intended to do:

https://github.com/koutheir/selinux/blob/aa0fe914b0cc4f461f4b417f61c8cec290bd9218/selinux/src/call_back/tests.rs#L31

What this will do is convert the address of `libc::abort` into a `*const fn ...`, and then *load from that address*. IOW this loads the first 8 bytes of the text of that function, and then treats them as a function pointer which is passed to `template`. Probably what this meant to do is transmute the function pointer: `template::<super::Log>(transmute(libc::abort as fn() -> !))`.

(via [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/inlining.20and.20instruction_set.20reference.231307/near/319444564))

**Comment by koutheir** [comment]
Your assumed intention is correct. Thank you for the catch! I'll fix this soon.

**Comment by koutheir** [comment]
[This commit](https://github.com/koutheir/selinux/commit/a5c15c542a3d3540d68a2be1dd0f34c157067a44) fixes this issue.

**Comment by koutheir** [comment]
Version `0.3.3` fixes this issue. Thank you!

**Comment by RalfJung** [comment]
Note that "*const unsafe fn() -> !" is a *pointer to a function pointer* (double indirection). If that's what you want then this is fine. :)

**Comment by koutheir** [comment]
That is definitely not what I wanted. I followed [this documentation](https://rust-lang.github.io/unsafe-code-guidelines/layout/function-pointers.html#representation). Did I miss something?

**Comment by koutheir** [comment]
Does this mean that my new code transforms `libc::abort` into a pointer to a function pointer, and then transforms that double pointer into a pointer to the new prototype?

**Comment by RalfJung** [comment]
Ah right, the *data* is actually fine -- `abort_ptr` is a function pointer. You just picked a strange type for it. I would have written
```rust
let abort_ptr = libc::abort as unsafe fn() -> !;
```
which is equivalent in terms of the data but now the type actually matches the data.

You could also have used
```rust
let abort_ptr = libc::abort as *const ();
```
to very explicitly not care about the type. That's what the docs you linked do. Any type `T` instead of `()` also works. The fact that you picked a function pointer type for `T` is what made it unnecessarily confusing.

**Comment by koutheir** [comment]
> `let abort_ptr = libc::abort as unsafe fn() -> !;`

But then `mem::transmute()` would refuse to perform the casting. `mem::transmute()` itself hints that I need to create a pointer because the function pointer types are zero-sized.

> `let abort_ptr = libc::abort as *const ();`

I wanted to avoid casting the function pointer into a data pointer. I wanted to keep the "function pointer" nature of the data throughout the conversion. But if the pointer I created was actually a double pointer, then I didn't actually achieve this. Did I?

**Comment by RalfJung** [comment]
> I wanted to avoid casting the function pointer into a data pointer. I wanted to keep the "function pointer" nature of the data throughout the conversion. But if the pointer I created was actually a double pointer, then I didn't actually achieve this. Did I?

You did not, you are casting to a data pointer.

> But then mem::transmute() would refuse to perform the casting. mem::transmute() itself hints that I need to create a pointer because the function pointer types are zero-sized.

Not sure what you mean, this compiles fine here:
```rust
fn main() {
    let abort_ptr = libc::abort as unsafe extern "C" fn() -> !;
    let transmuted_ptr: extern "C" fn(i32, ...) -> () = unsafe { std::mem::transmute(abort_ptr) };
}
```

**Comment by koutheir** [comment]
I mean this conversion fails:
```rust
let abort: unsafe extern "C" fn(c_int, *const c_char, ...) -> c_int =
    unsafe { mem::transmute(libc::abort) };
```

with the error:
```
error[E0591]: can't transmute zero-sized type
  --> selinux/src/call_back/tests.rs:43:18
   |
43 |         unsafe { mem::transmute(libc::abort) };
   |                  ^^^^^^^^^^^^^^
   |
   = note: source type: unsafe extern "C" fn() -> ! {libc::abort}
   = note: target type: unsafe extern "C" fn(i32, *const i8, ...) -> i32
   = help: cast with `as` to a pointer instead
```

For some reason I don't understand, this works:
```rust
let abort: unsafe extern "C" fn(c_int, *const c_char, ...) -> c_int =
    unsafe { mem::transmute(libc::abort as unsafe extern "C" fn() -> !) };
```

Isn't `libc::abort` already of the type `unsafe extern "C" fn() -> !`? Or is it of the type `FnMut`?

**Comment by RalfJung** [comment]
You are running into the common issue of confusing "function items" with "function pointers". See https://doc.rust-lang.org/reference/types/function-item.html, https://doc.rust-lang.org/reference/types/function-pointer.html.

`libc::abort` denotes a value of size 0 of an unnameable type that uniquely identifies this one function. It can be cast to `unsafe extern "C" fn() -> !` which turns the function item into a function pointer.

**Comment by koutheir** [comment]
Thank you for the explanation! I didn't know Rust thinks like this about functions.

I'll update the code to become:
```rust
template::<super::Log>(unsafe { mem::transmute(libc::abort as unsafe extern "C" fn() -> !) });
```

**Comment by koutheir** [comment]
[More correct commit](https://github.com/koutheir/selinux/commit/f95a8379c2b79bab2f4e8b43e68e23f5a917084d).
